language: node_js
dist: focal
node_js:
  - 18
before_script:
  - npm install
script: npm run build:stylus && eleventy --pathprefix=eleventy-stylus-blog-theme
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  
  keep-history: true
  target_branch: gh-pages
  on:
    branch: main
